mm-video: fix arithmetic on a pointer to void
Use char* instead of void* for this pointer arithmetic.
Fixes the following:

error: arithmetic on a pointer to void
(vdec_msg->msgdata.output_frame.bufferaddr +